### ISSUE TITLE
[Bug] Cron does not accept the valid symbolic names for dayWeek

### ISSUE THREAD

**Issue by Vampire** [krzema12/github-workflows-kt#642]
# Action

```kts
Cron(
    minute = "0",
    hour = "0",
    dayWeek = "FRI"
)
```

# Expected

Valid symbolic names for `dayWeek` to be accepted.

# Actual

```plain
java.lang.IllegalStateException: Your Cron syntax [0 0 * * FRI] contains errors:
- Field 'dayWeek' with value [FRI] contains invalid characters
	at it.krzeminski.githubactions.domain.triggers.ScheduleKt.Cron(Schedule.kt:32)
	at it.krzeminski.githubactions.domain.triggers.ScheduleKt.Cron$default(Schedule.kt:16)
	at Check_dependency_versions_main.<init>(check-dependency-versions.main.kts:34)
```

# Workaround, if exists

Using numeric values instead

# Library version

v0.35.0

**Comment by krzema12** [comment]
Actually we can make it more type-safe by having an overload that accepts some enum with weekday names.
